const Vec3 = require('vec3')
module.exports = {
	faces: [
		new Vec3(0, -1, 0),
		new Vec3(0, 1, 0),
		new Vec3(0, 0, -1),
		new Vec3(0, 0, 1),
		new Vec3(-1, 0, 0,),
		new Vec3(1, 0, 0,),
	],
	foodItems: [
		"apple",
		"appleEnchanted",
		"baked_potato",
		"beef",
		"beetroot_soup",
		"beetroot",
		"bread",
		"carrot",
		"chicken",
		"chorus_fruit",
		"clownfish",
		"cooked_beef",
		"cooked_chicken",
		"cooked_fish",
		"cooked_porkchop",
		"cooked_rabbit",
		"cooked_salmon",
		"cookie",
		"fish",
		"golden_apple",
		"golden_carrot",
		"honey_bottle",
		"melon",
		"mushroom_stew",
		"muttonCooked",
		"muttonRaw",
		"porkchop",
		"potato",
		"pumpkin_pie",
		"rabbit_stew",
		"rabbit",
		"salmon",
		"sweet_berries"
	],
	"stuffPriority": ["axe", "sword", "pickaxe", "shovel"],
	"stuffPriorityTools": ["axe", "sword", "pickaxe", "shovel"],
	"materialPriority": ["diamond", "iron"]

}